spring:
  datasource:
    username: fromConfigServer
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/book?createDatabaseIfNotExist=true
    password: fromConfigServer
username: FromConfigServer
url: test.com from config
